services:
  api:
    build: ./api/
    environment:
      - PORT=5000
    ports:
      - 5000:5000

  webapp:
    build: ./webapp/
    environment:
      - VITE_API_URL=/api
    ports:
      - 3000:3000
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
