services:
  api:
    build: ./api/
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: password123
      PGDATABASE: geotimelapse
      PORT: 3001
    ports:
      - 3001:3001
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: geotimelapse

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  webapp:
    build: ./webapp/
    environment:
      - VITE_API_URL=/api
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
