services:
  api:
    build: ./backend/
    environment:
      - PORT=5000
    ports:
      - 5000:5000

  webapp:
    build: ./frontend/
    environment:
      - API_URL=http://api:5000
      - PORT=3000
    ports:
      - 3000:3000
