services:
  api:
    build: ./backend/
    environment:
      - PORT=5001
    ports:
      - 5001:5001

  webapp:
    build: ./frontend/
    environment:
      - VITE_API_URL=http://localhost:5001
    ports:
      - 4173:4173
