services:
  api:
    build: ./backend/
    environment:
      - PORT=5000
    ports:
      - 5000:5000

  webapp:
    build: ./frontend/
    environment:
      - API_URL=http://api:5000
    ports:
      - 4173:4173
